name: Check my friends

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Cache pickle files
        id: cache-data
        uses: actions/cache@v5
        with:
          path: checkrobloxfriends.pk
          key: checkrobloxfriends-pk-${{ github.run_id }}
          restore-keys: |
            checkrobloxfriends-pk-

      - name: Run script
        env:
          ROBLOX_COOKIE: ${{ secrets.ROBLOX_COOKIE }}
          ROBLOX_USER_ID: ${{ secrets.ROBLOX_USER_ID }}
          SMTP_SERVER: ${{ secrets.SMTP_SERVER }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
          SMTP_USERNAME: ${{ secrets.SMTP_USERNAME }}
          SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
          SMTP_FROM_ADDRESS: ${{ secrets.SMTP_FROM_ADDRESS }}
          SMTP_TO_ADDRESS: ${{ secrets.SMTP_TO_ADDRESS }}
        run: python checkrobloxfriends.py